### PR TITLE
Update OnboardingRequest contract

### PR DESCRIPTION
**Pull request by krystay**
- Rename Country to CountryRegion
- Rename State to StateProvince

### CODE REVIEW

**Comment by krystay** [comment]
I was having trouble getting the auto-generation tool set up and running on my machine, so I ended up editing it manually since it was such a small change. Is that OK? I can try to redo it through the tool if necessary.

Yes, these changes are for sprint 68.

**Comment by brendankowitz** [comment]
We *should* avoid manual edits, but this should be ok so long as we've confirmed that the changes are included in the new swagger file.

**Comment by brendankowitz** [comment]
@davidkwoods we also should note this could be breaking for existing apps

**Comment by krystay** [comment]
@brendankowitz @davidkwoods  Yup, these changes are in Swagger, and @jhutchings1 and @rouellam are good with communicating the breaking changes.

**Pull request closed without merging**
